<section class="page-heading compact-heading"><div><p class="eyebrow">YOUR MOMENTUM</p><h1>Study <span>progress.</span></h1><p class="heading-copy">Notice what's done, then choose what's next.</p></div><a class="primary-button heading-action" href="<?= e(url('/tasks')) ?>">Review tasks</a></section>
<section class="progress-summary content-section"><div class="progress-ring" style="--progress: <?= (int) $progress ?>"><div><strong><?= (int) $progress ?><small>%</small></strong><span>complete</span></div></div><div class="progress-copy"><p class="eyebrow">YOUR PLAN AT A GLANCE</p><h2><?= count($completed) ?> of <?= (int) $total ?> tasks completed</h2><p class="muted-copy"><?= $total === 0 ? 'Add a task when you are ready to get started.' : (count($pending) === 0 ? 'Everything on your list is complete. Nicely done.' : count($pending) . ' tasks are still waiting for you.') ?></p></div></section>
<section class="progress-columns">
    <div class="content-section"><div class="section-heading"><div><p class="eyebrow">READY WHEN YOU ARE</p><h2>Pending <span class="count-chip"><?= count($pending) ?></span></h2></div></div>
        <?php if ($pending === []): ?><div class="empty-state compact-empty"><h3>Nothing pending</h3><p>Your next task can wait until you're ready to add it.</p></div><?php else: ?><ul class="progress-task-list"><?php foreach ($pending as $task): ?><li><div class="task-details"><a class="task-title task-link" href="<?= e(url('/tasks/' . $task['id'] . '/edit')) ?>"><?= e($task['title']) ?></a><span class="task-meta"><?= e($task['subject_name'] ?? 'No subject') ?><?php if ($task['due_date']): ?><span class="dot-separator">·</span><?= e(date('M j', strtotime($task['due_date']))) ?><?php endif; ?></span></div><span class="status-pill status-<?= e($task['status']) ?>"><?= e(ucwords(str_replace('_', ' ', $task['status']))) ?></span></li><?php endforeach; ?></ul><?php endif; ?>
    </div>
    <div class="content-section"><div class="section-heading"><div><p class="eyebrow">LOOK HOW FAR YOU'VE COME</p><h2>Completed <span class="count-chip"><?= count($completed) ?></span></h2></div></div>
        <?php if ($completed === []): ?><div class="empty-state compact-empty"><h3>Your first win is ahead</h3><p>Completed tasks will collect here as you make progress.</p></div><?php else: ?><ul class="progress-task-list"><?php foreach ($completed as $task): ?><li class="is-complete"><div class="task-details"><a class="task-title task-link" href="<?= e(url('/tasks/' . $task['id'] . '/edit')) ?>"><?= e($task['title']) ?></a><span class="task-meta"><?= e($task['subject_name'] ?? 'No subject') ?></span></div><span class="complete-mark" aria-label="Completed">✓</span></li><?php endforeach; ?></ul><?php endif; ?>
    </div>
</section>